image: docker:latest

variables:
  SQL_HOST: 'db'
  SQL_PORT: '5432'
  DATABASE: 'postgres'
  APP_FOLDER: '/usr/src/app/tmtar'
  DB_INIT: 'True'

stages:
  - build
  - test
  - release
  - cleanup
before_script:
  - apk add --update py-pip &&
      pip install docker-compose
build:
  tags: 
    - docker
  stage: build
  before_script:
    - export
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD registry.gitlab.com
  script:
    #- docker pull registry.gitlab.com/baltazar1697/tmtar_api 
    - docker build --cache-from registry.gitlab.com/baltazar1697/tmtar_api -t registry.gitlab.com/baltazar1697/tmtar_api:$CI_BUILD_REF -tag registry.gitlab.com/baltazar1697/tmtar_api:latest .
    
    - docker push registry.gitlab.com/baltazar1697/tmtar_api:$CI_BUILD_REF
    - docker push registry.gitlab.com/baltazar1697/tmtar_api:latest
    
  artifacts:
    paths:
      - services/web
    expire_in: never

test:
  tags:
    - docker
  stage: test
  script:
    - cd services/web
    - pip install tmtar/requirements.txt
    - pytest ./tmtar --durations=0

cleanup_job:
  tags:
    - docker
  stage: cleanup
  script:
    - docker rm -v build_data_$CI_PROJECT_ID_$CI_BUILD_REF
    - docker rmi ci-project-build-$CI_PROJECT_ID:$CI_BUILD_REF
  when: always
