image: docker:stable
services: 
  - docker:dind

variables:
  SQL_HOST: 'db'
  SQL_PORT: '5432'
  DATABASE: 'postgres'
  APP_FOLDER: '/usr/src/app/tmtar'
  DB_INIT: 'True'

stages:
  - build
  - test
  - release


build:
  tags: 
    - docker
  stage: build
  before_script:
    - apk add --no-cache docker-compose
    - export
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD registry.gitlab.com
  script:
    - docker pull registry.gitlab.com/baltazar1697/tmtar_api 
    - docker build --cache-from registry.gitlab.com/baltazar1697/tmtar_api -t registry.gitlab.com/baltazar1697/tmtar_api:$CI_BUILD_REF -tag registry.gitlab.com/baltazar1697/tmtar_api:latest --tag registry.gitlab.com/baltazar1697/tmtar_api services/web/
    - docker push registry.gitlab.com/baltazar1697/tmtar_api:$CI_BUILD_REF
    - docker push registry.gitlab.com/baltazar1697/tmtar_api:latest
    
  artifacts:
    paths:
      - services/web
    expire_in: never

test:
  tags:
    - test
  stage: test
  before_script:
    - apk add --no-cache docker-compose
  script:
    - pytest ./tmtar --durations=0 --junitxml=report.xml
  allow_failure: true
  artifacts:
    when: always
    reports:
      junit: report.xml 

#deploy:
 # stage: release
 # before_script:
 #   - apk add --no-cache docker-compose
  # script:
  #   - docker-compose -f docker-compose.prod.yml build
  #   #- docker-compose exec web python manage.py db upgrade
