image: docker:stable

variables:
  SQL_HOST: 'db'
  SQL_PORT: '5432'
  DATABASE: 'postgres'
  APP_FOLDER: '/usr/src/app/tmtar'
  DB_INIT: 'True'

stages:
  - build
  - test
  - release

before_script:
  - apk add --update py-pip &&
      pip install docker-compose
build:
  tags: 
    - docker
  stage: build
  before_script:
    - export
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD registry.gitlab.com
  script:
    #- docker pull registry.gitlab.com/baltazar1697/tmtar_api 
    - docker build --cache-from registry.gitlab.com/baltazar1697/tmtar_api -t registry.gitlab.com/baltazar1697/tmtar_api:$CI_BUILD_REF -tag registry.gitlab.com/baltazar1697/tmtar_api:latest .
    
    - docker push registry.gitlab.com/baltazar1697/tmtar_api:$CI_BUILD_REF
    - docker push registry.gitlab.com/baltazar1697/tmtar_api:latest
    
  artifacts:
    paths:
      - services/web
    expire_in: never

test:
  tags:
    - docker
  stage: test
  script:
    - docker-compose -f docker-compose.test.yml up 

deploy:
  stage: release
  script:
    - docker-compose -f docker-compose.prod.yml down
    - docker-compose -f docker-compose.prod.yml up -d
    #- docker-compose -f docker-compose.prod.yml python manage.py db upgrade