variables:
  SQL_HOST: 'db'
  SQL_PORT: '5432'
  DATABASE: 'postgres'
  APP_FOLDER: '/usr/src/app/tmtar'
  DB_INIT: 'True'

stages:
  - build
  - test
  - release

build:
  stage: build
  image: docker:stable
  tags: 
    - docker
  services: 
  - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD registry.gitlab.com
  script:
    - docker pull registry.gitlab.com/baltazar1697/tmtar_api 
    - docker build --cache-from registry.gitlab.com/baltazar1697/tmtar_api -t registry.gitlab.com/baltazar1697/tmtar_api:$CI_BUILD_REF --tag registry.gitlab.com/baltazar1697/tmtar_api:latest --tag registry.gitlab.com/baltazar1697/tmtar_api services/web/
    - docker push registry.gitlab.com/baltazar1697/tmtar_api:$CI_BUILD_REF
    - docker push registry.gitlab.com/baltazar1697/tmtar_api:latest
test:
  stage: test
  image: python:3.7
  before_script:
    - pip3 install pytest docker-compose
  script:
    - docker-compose -f docker-compose.test.yml up
  allow_failure: true
  after_script:
    - docker-compose down
  artifacts:
    when: always
    reports:
      junit: report.xml 

#deploy:
 # stage: release
 # before_script:
 #   - apk add --no-cache docker-compose
  # script:
  #   - docker-compose -f docker-compose.prod.yml build
  #   - docker-compose exec web python manage.py db upgrade
