version: '3.7'
services:
  web:
    build: 
      context: ./services/web
      dockerfile: Dockerfile
    command: bash -c "
      flakehell lint --tee --output-file=codestyle.json ./services/ 
      && pytest ./tmtar --durations=0 --junitxml=report.xml"
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./env/.env
      - ./env/.env.dev
    networks:
      - api

  db:
    image: postgres:latest
    ports:
    - 5432:5432
    volumes:
      - ./create_db.sh:/docker-entrypoint-initdb.d/create_db.sh
    env_file:
      - env/.env.db
    networks:
      - api

networks:
  api: