version: '3.7'
services:
  web:
    build:
      context: ./services/web
      dockerfile: Dockerfile.prod
    command: gunicorn --bind 0.0.0.0:5000 "wsgi:start_app()"
    volumes:
      - media_volume:/home/app/web/project/tmtar/media
    expose:
      - 5000
    env_file:
      - ./env/.env
      - ./env/.env.prod
    depends_on:
      - db

  db:
    image: crunchydata/crunchy-postgres-gis:centos8-13.3-3.1-4.6.3
    hostname: db
    ports:
    - 5432:5432
    volumes:
      - ./configs:/pgconf
      - db-pgdata:/pgdata
      - db-wal:/pgwal
      - db-backup:/backrestrepo
    env_file:
      - env/.env.db
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  nginx:
    build: ./services/nginx
    volumes:
      - media_volume:/home/app/web/project/tmtar/media
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  media_volume:
  db-pgdata:
  db-wal:
  db-backup: