version: '3.7'
services:
  web:
    build: ./services/web
    command: bash -c "
      flakehell lint --tee --output-file=codestyle.json ./services/ 
      && pytest ./tmtar --durations=0 --junitxml=report.xml"
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./env/.env
      - ./env/.env.dev
    networks:
      - api

  db:
    image: postgres:latest
    ports:
    - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=tmtar_user
      - POSTGRES_PASSWORD=dfgBNM3689
      - POSTGRES_DB=tmtar_test
    networks:
      - api

volumes:
  postgres_data:

networks:
  api: