version: '3.7'
services:
  web:
    build: ./services/web
    command: python wsgi.py
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./env/.env
      - ./env/.env.dev
    networks:
      - api

  db:
    image: postgres:latest
    ports:
    - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./create_db.sh:/docker-entrypoint-initdb.d/create_db.sh
    env_file:
      - env/.env.db
    networks:
      - api

volumes:
  postgres_data:

networks:
  api: