version: '3.7'
services:
  web:
    build: ./services/web
    command: pytest ./tmtar/locations/service_test.py
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
  db:
    image: postgres:12-alpine
    ports:
    - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=tmtar_user
      - POSTGRES_PASSWORD=dfgBNM3689
      - POSTGRES_DB=tmtar_dev

volumes:
  postgres_data: