version: '3.7'
services:
  web:
    build: ./services/web
    command: python wsgi.py
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./env/.env
      - ./env/.env.dev
    networks:
      - api

  db:
    image: crunchydata/crunchy-postgres-gis:centos8-13.3-3.1-4.6.3
    networks:
      - api
    ports:
    - 5432:5432
    volumes:
      - ./configs:/pgconf
      - db-pgdata:/pgdata
      - db-wal:/pgwal
      - db-backup:/backrestrepo
    env_file:
      - env/.env.db
  
  admin:
    container_name: admin_panel
    command: npm start
    build:
      context: ./services/frontend
      dockerfile: Dockerfile
    volumes:
      - ./services/frontend:/app
      - /app/node_modules
    ports:
      - 4200:4200

networks:
  api:

volumes:
  db-pgdata:
  db-wal:
  db-backup: