version: '3.7'
services:
  web:
    build: 
      context: ./services/web
      dockerfile: Dockerfile
    command: bash -c "
      flake8 --tee --output-file=codestyle.log .
      && pytest ./tmtar -v --junitxml=report.xml"
    volumes:
      - ./services/web/:/usr/src/app/
      - ./.flake8:/usr/src/app/.flake8
    ports:
      - 5000:5000
    env_file:
      - ./env/.env
      - ./env/.env.dev
    networks:
      - api

  db:
    image: crunchydata/crunchy-postgres-gis:centos8-13.3-3.1-4.6.3
    hostname: db
    ports:
    - 5432:5432
    volumes:
      - ./configs:/pgconf
      - db-pgdata:/pgdata
      - db-wal:/pgwal
      - db-backup:/backrestrepo
    env_file:
      - env/.env.db
    networks:
      - api

  admin:
    container_name: admin_panel
    command: npm test
    build:
      context: ./services/frontend
      dockerfile: Dockerfile
    volumes:
      - ./services/frontend:/app
      - /app/node_modules
    ports:
      - 9876:9876

networks:
  api:

volumes:
  db-pgdata:
  db-wal:
  db-backup:
