[tool.flakehell]
format = "grouped"
show_source = true
statistics = false
doctests = true
enable_extensions = "G"

accept_encodings = "utf-8"
max_complexity = 10
max_line_length = 80

ignore = "S104,D100,WPS300,WPS412,D104,D101,WPS305,WPS433,WPS226,WPS213,WPS232,WPS231,WPS430"
exclude = [".git,__pycache__,*test.py,fixtures.py,events,objects"]
docstring_style="sphinx"
strictness="short"

[tool.flakehell.plugins]
"wemake-python-styleguide" = ["+*"]
"flake8-*" = ["+*"]