FROM python:3.7.8-slim-buster

WORKDIR /usr/src/app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apt-get update && apt-get install -y netcat

RUN pip install --upgrade pip
COPY tmtar/requirements.txt /usr/src/app/requirements.txt
RUN pip install -r requirements.txt
RUN pip install flake8 wemake-python-styleguide


COPY . /usr/src/app/

CMD flake8 .

ENTRYPOINT ["/usr/src/app/entrypoint.sh"]