version: '3.7'

services:
  admin:
    container_name: admin
    build:
      context: ./services/frontend
      dockerfile: Dockerfile.prod
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 80:80
