version: '3.7'

services:

  admin:
    container_name: takemetoar-prod
    command: npm run start:prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 4200:4200
